.TH "" "" "" "" ""
.SH vz\-book\-cli
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ vz\-book\-cli
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ vz\-book\-cli\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ vz\-book\-cli

Commands:

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
initial commit \-\- Jan 31st
16 (../../commit/cc485da319520fb5a033640fc0bd7cd458132ad5)
.SH Bug fixes
.IP \[bu] 2
update to latest lodash \-\- Jan 31st
16 (../../commit/17cca485adf33c68603645df2ff0388dfd20e646)
